hyperledger/sawtooth-pbft

Dockerfile
Jenkinsfile
src/config.rs
src/main.rs
src/message_log.rs
src/node.rs

Move to stable clippy

---

Jenkinsfile
docker-compose.yml
src/config.rs
src/engine.rs
src/handlers.rs
src/main.rs
src/node.rs
src/state.rs
tests/test_liveness.yaml

This PR gets PBFT building properly on Jenkins once more, and includes various fixes to enable that.

Make PBFT work on Jenkins

---

docker-compose-installed.yaml
src/config.rs
src/engine.rs
src/handlers.rs
src/node.rs
src/state.rs

Implements this RFC: https://github.com/hyperledger/sawtooth-rfcs/pull/29

Regular view changes

---

src/config.rs
src/engine.rs
src/error.rs
src/handlers.rs
src/main.rs
src/message_log.rs
src/node.rs
src/state.rs
src/storage/disk.rs
src/storage/memory.rs
src/storage/mod.rs
src/timing.rs

Groups imports into `std`, external, and internal dependencies

Reformat imports to improve readability

---

adhoc/.env
adhoc/admin.yaml
adhoc/node.yaml
adhoc/workload.yaml
tests/sawtooth-pbft-test.dockerfile
tests/test_crash_fault_tolerance.sh
tests/test_crash_fault_tolerance.yaml

This adds, but does not enable, a CFT integration test. We are currently working on the known issues that must be resolved for this test.

Add CFT integration test

---

Cargo.toml
protos/pbft_message.proto
src/config.rs
src/engine.rs
src/handlers.rs
src/hash.rs
src/main.rs
src/message_extensions.rs
src/message_log.rs
src/message_type.rs
src/node.rs
src/state.rs

Includes refactoring of the stored messages to include metadata used in construction of the consensus seal

Add consensus seal to PBFT

---

bin/run_docker_test
tests/test_dynamic_membership.sh
tests/test_dynamic_membership.yaml

Adds a dynamic membership test that starts a network, adds/removes
nodes, and makes sure that all nodes in the network make progress.

Dynamic membership tests

---

adhoc/node.yaml
tests/client.yaml
tests/grafana.yaml
tests/test_liveness.yaml

Updates the consensus settings in all integration tests to be compatible with
the new validator enforcement rules.
Signed-off-by: Adam Ludvik <ludvik@bitwise.io>

Update settings for validator enforcement rules

---

docs/source/installing-and-running-pbft.rst
docs/source/technical-information.rst

- Change title and add intro text to clarify that this procedure describes how
to run PBFT tests
- Reorganize and expand several steps to clarify what's being done
- Move the optional items under "Optional Changes" and expand with specific
information for each
- Fix the link to the PBFT on-chain settings
- Reword and reformat to match Sawtooth doc standards

Edit and retitle PBFT install+test procedure

---

src/node.rs

Handles the case where a node doesn't have a working block and gets a blocknew message that it could catch up from.

Handle no working block in node catchup

---

Jenkinsfile
docs/Dockerfile

Build docs in Jenkins

---

README.md

- Edit content and link text for clarity
- Update the Motivation section to reflect the current 1.1 release
and PoET information (because PoET-SGX is BFT).
- Correct the RFC links
- Add Documentation section with a link to the docs subdirectory in the repo
- Add License information

Update PBFT README

---

protos/pbft_message.proto
src/config.rs
src/engine.rs
src/error.rs
src/handlers.rs
src/message_extensions.rs
src/message_log.rs
src/message_type.rs
src/node.rs
src/state.rs

A variety of feature implementations, fixes, and improvements for view changing in PBFT.

Fix view changes

---

README.md
docs/source/introduction-to-sawtooth-pbft.rst

Also add link to main repo README for current project status.

Add links to published PBFT docs and rustdocs

---

Cargo.toml

Update Cargo.toml with new sawtooth-sdk repo

---

docs/Dockerfile
src/node.rs

Unpin the sphinx doc dependency and add latexmk for pdf builds under the latest release

Unpin Sphinx Dependency

---

src/message_log.rs
src/node.rs

Collection of fixes and enhancements for PBFT

Miscellaneous fixes

---

Jenkinsfile

Signed-off-by: Richard Berg <rberg@bitwise.io>

Update Jenkinsfile to schedule a build at 3AM CST

---

src/node.rs

Fixes a bug where, when a new block and its PrePrepare
message are received before the previous block gets committed, the node
will never switch to Preparing that block. To fix this, the node will
now try to switch to Preparing when one of three things happens:
- A PrePrepare is received; if the PrePrepare is for the current
sequence number and the node already has the block the message is for,
it can switch to Preparing
- A new block is received; if the block is for the current sequence
number and the node already has the PrePrepare for the block, it can
switch to Preparing.
- A block was just committed; if the node already has a block for its
next sequence number and a PrePrepare for that block, it can switch to
Preparing.

Fix pre preparing

---

docs/source/architecture.rst

- Add intro text to summarize Sawtooth PBFT architecture at a high level
- Add "Network Overview" section to describe fault tolerance (max number of
faulty nodes), view changes, sequence numbers, and info stored by each node.
Also, summarize on-chain settings with a link to that section.
- Delete the last section, "Node Information Storage", because that information
is now in "Network Overview"

Add PBFT architecture intro and network overview

---

Cargo.toml

Signed-off-by: Andrea Gunderson <agunde@bitwise.io>

Update PBFT to use Sawtooth Rust SDK 0.2

---

src/config.rs
src/hash.rs
src/message_log.rs
src/message_type.rs
src/node.rs
src/state.rs
src/timing.rs

Lots and lots of simplifications and enhancements

Minor improvements (part 1)

---

docs/source/architecture.rst

Add log pruning/garbage collection info to Arch doc

---

src/node.rs
src/state.rs

Don't update view when membership is changed and remove BlockCommit ignoring

Update block commit handling

---

src/error.rs
src/node.rs

Fix log message and don't view change when an invalid NewView is received

Update new view handling

---

ci/nightly/sawtooth-pbft-engine

Add nightly dockerfile

---

src/hash.rs
src/main.rs
src/message_log.rs
src/message_type.rs
src/state.rs
src/test_helpers.rs
src/timing.rs

Add message parsing, log, state, and initialization tests

Add auxiliary tests

---

src/message_type.rs

This commit fixes a vulnerability that would allow a malicious node to
arbitrarily crash another node's PBFT engine.
When parsing messages from peers, nodes use the type indicated in the
header of the PeerMessage; however, this type field can be set
arbitrarily and could be set to a different value than the contained
PBFT message's type. Some of the accessors for ParsedMessages panic if
called on the wrong type of ParsedMessage (e.g. calling get_seal on a
ParsedMessage containing a NewView), so there must be a mechanism to
guard against a bad message triggering a panic.
This is fixed by simply checking and ensuring that the ParsedMessage's
type matches the type of the PeerMessage. An alternative would be to
remove the panics in the accessors, but those are useful for ensuring
that no …

Fix ParsedMessage type vulnerability

---

Cargo.toml

This should match the VERSION file, and be incremented after release.
Signed-off-by: Richard Berg <rberg@bitwise.io>

Update Cargo.toml to version 0.1.2

---

docs/source/index.rst
docs/source/using-pbft-consensus.rst

- Summarize PBFT requirements and helpful tips
- Link to procedures in the Sawtooth App Dev and Sys Admin Guide

Add 'Using PBFT Consensus' section to PBFT doc

---

docs/source/installing-and-running-pbft.rst
tests/test_liveness.yaml

Signed-off-by: Andrea Gunderson <agunde@bitwise.io>

Remove old setting from installing and testing doc

---

docs/source/architecture.rst

Update view changing docs

---

src/engine.rs

Fixes the usage of the `Ticker` in the main engine loop; this `Ticker`
is intended to act as a timeout so that block publishing is only
attempted after a given duration. However, the timeout checking (used to
trigger view changes) was also occuring in this `Ticker`; this meant
that these timeouts were only ever being checked when the block
duration had passed. These should not be tied together, so this commit
separates them and gives the ticker a more appropriate name.

Fix usage of the Ticker in the main engine loop

---

docs/source/architecture.rst
docs/source/configuring-pbft.rst
docs/source/index.rst
docs/source/installing-and-running-pbft.rst
docs/source/on-chain-settings.rst
docs/source/using-pbft-consensus.rst
src/config.rs
src/engine.rs
src/main.rs
src/node.rs
src/state.rs
src/test_helpers.rs
tests/client.yaml
tests/grafana.yaml
tests/test_liveness.yaml

Updates config variable names, makes settings that only affect local operation CLI args instead of on-chain settings, updates default values and documentation
PRs will be put up to reflect these changes in sawtooth-core and sawtooth-website

Settings config update

---

src/node.rs

When a view change is performed, the old primary should cancel any block
it may have initialized; if/when it becomes primary again in the future,
it will need initialize a new block that is built on top of the new
chain head.
This fixes a bug where nodes would get stuck because an old intialized
block was never cancelled.

On view change, old primary should cancel block

---

docs/source/architecture.rst
docs/source/glossary.rst

Fix broken links to Message Types + View Changes doc

---

ci/sawtooth-pbft-engine

Update ci dockerfile to install from chime repo

---

Cargo.toml
src/engine.rs

Update sawtooth SDK to v0.4

---

src/node.rs

Fix clippy lint from 1.40 update

---

RELEASE_NOTES.md

Add v1.0.2 release notes

---

RELEASE_NOTES.md

Add release notes for v1.0.3

---

CODEOWNERS
MAINTAINERS.md

They have previously indicated they wished to be retired.

Retire Anne and Logan from maintainers and codeowners
