- src/engine.rs
Corresponds to [sawtooth-core#1903](https://github.com/hyperledger/sawtooth-core/pull/1903)
> Return Result in Engine::start

- src/engine.rs
- src/handlers.rs
- src/message_log.rs
- src/node.rs
Adds a verification step for all PBFT messages that compares the
signer_id of the message with the sender_id provided by the validator;
if they do not match, the message is ignored. Since the validator
verifies all peer messages it receives, we can use the sender_id as a
guarantee of who sent the message.
> Update message signing usage

- Jenkinsfile
Jenkins restricts builds to particular labels, and `agent any` doesn't override that. This change makes PBFT build on nodes matching the `master` label.
> Build PBFT on Jenkins nodes matching label

- Cargo.toml
- build.rs
- src/config.rs
- src/engine.rs
- src/main.rs
- src/node.rs
- src/state.rs
- src/storage/disk.rs
- src/storage/memory.rs
- src/storage/mod.rs
- src/timing.rs
Introduces `Storage` trait that ensures that modifications to an object are synced to a backing store using RAII, and wraps `PbftState` in that. Also moves `PbftState` to be state managed by the engine, for two reasons:
* `PbftNode` requiring `&mut self` on its methods and also having it hand out references to a contained `PbftState` didn't play nicely with lifetimes
*  Syncing changes only at the end of each engine loop means we don't have to worry about whether or not any state changes within an engine loop need to be atomic, each loop either gets synced or not
> Add Storage trait for PbftState

- Cargo.toml
`cargo deb` was complaining about missing fields in Cargo.toml, this adds in those missing fields
> Add metadata for cargo deb

- Cargo.toml
Alphabetizes dependencies listed in Cargo.toml to improve readability.
> Order dependencies in Cargo.toml for readability

- src/handlers.rs
- src/state.rs
Moves free-floating function that takes only `PbftState` as parameter to method of `PbftState`.
> Refactor PbftState block discard logic into method

- tests/test_liveness.yaml
Update the peering configuration in the liveness test to eliminate the chance
of creating duplicate connections between nodes. Because connections are
bi-directional, only one node per pair of nodes needs to list the other node as
a peer.
Signed-off-by: Adam Ludvik <ludvik@bitwise.io>
> Remove duplicates from test peering configuration

- Cargo.toml
`rust-protobuf` recently switched to using `clippy::all`, which breaks things on stable. Pinning PBFT to previous version until that gets sorted out.
> Pin protobuf dependency

- src/engine.rs
- src/handlers.rs
- src/message_log.rs
- src/node.rs
- tests/sawtooth-pbft-test.dockerfile
The Consensus API was recently updated, and most importantly, the PeerMessage type should now be treated as opaque. This commit eliminates construction of PeerMessages in PBFT, and instead passes around the raw bytes from the received PeerMessage.
> Handle Consensus SDK updates

- Jenkinsfile
Denying `clippy` warnings is now deprecated in favor of denying `clippy::all` warnings
> Update name of clippy rustfmt argument

- Cargo.toml
Followup to #31. The maintainer of rust-protobuf helpfully pushed out a patched version with the breaking commit removed, so unpinning the version.
> Unpin rust-protobuf dependency

- src/node.rs
`assert!(a == b)` can be written as `assert_eq!(a, b)`
> Fix assert_eq! lint

- src/node.rs
Attempting to subtract a number on a usize that results in a negative number will cause a panic in Rust. That was happening in a test case, and getting caught with `catch_unwind`. We can convert that to `checked_sub` usage, and avoid dealing with panics.
> Convert bare usize subtraction to checked version

- src/message_extensions.rs
- src/message_log.rs
- src/node.rs
Moves lifetime specification from parameterized for the trait to parameterized by the `get_msg_info` method. We weren't relying on behavior specific to either style, and this lets us elide some lifetimes in code that uses the trait.
> Move PbftGetInfo trait lifetime to method lifetime

- src/handlers.rs
- src/message_log.rs
- src/node.rs
Moves logic that handles conditionally adding messages to PbftLog to be inside a method of PbftLog
> Move action_from_hint logic to PbftLog method

- Jenkinsfile
Ensures that resources are cleaned up, even if the liveness tests fail
> Always run docker compose down in Jenkinsfile

- Jenkinsfile
Jenkins is unable to properly cleanup if this isn't done.
> Chown artifacts to jenkins uid

- tests/sawtooth-services.yaml
- tests/test_crash_fault_tolerance.sh
- tests/test_crash_fault_tolerance.yaml
Moves sawtooth services defined in CFT compose file to separate compose file. This will let us reuse the compose file in any new tests, as well as avoid having to specify `--no-abort` when running the CFT compose file.
> Move CFT services to separate compose file

- src/node.rs
- tests/test_crash_fault_tolerance.sh
Adds a try_catchup method to PbftNode that is called on BlockNew that will attempt to catch the node up if it has fallen behind.
> Implement node catchup RFC

- src/config.rs
- src/engine.rs
- src/handlers.rs
- src/node.rs
- src/state.rs
- tests/test_dynamic_membership.sh
Implements membership changes for PBFT according to the following
procedure:
1. When a block is committed, check the list of peers in the
`sawtooth.consensus.pbft.peers` setting to see if it matches the current
list of peers stored in PBFT state.
2. If the 2 lists of peers differ, update the PBFT state's list of
peers, recalculate the value of f (max number of faulty nodes), and
force a view change.
> Implement dynamic membership

- docs/source/installing-and-running-pbft.rst
Make related changes in the Tips list (was called "Optional Changes"),
including:
- Mention script options; suggest using --help for more info
- Remove the "adding docker-compose options" tip because it doesn't work
with run_docker_test
- Reword for clarity
> Change PBFT test script to bin/run_docker_test

- build.rs
- src/config.rs
- src/engine.rs
- src/handlers.rs
- src/main.rs
- src/message_extensions.rs
- src/message_log.rs
- src/message_type.rs
- src/node.rs
- src/state.rs
- src/storage/disk.rs
- src/storage/memory.rs
- src/storage/mod.rs
`cargo fmt` updated recently and introduced new formatting. This updates PBFT to match the new formatting. Also fixes clippy lints.
> Updating code formatting with cargo fmt

- Cargo.toml
- src/main.rs
- src/message_log.rs
- src/node.rs
Forced view changes were causing issues with looking up votes for publishing by view number. The previous fix looked back a single view number, this provides a more general solution.
> Fix view number lookup issue

- src/state.rs
Helps when viewing PBFT output to include block number in addition to block ID.
> Display working block number for PbftState

- src/engine.rs
- src/error.rs
- src/handlers.rs
- src/message_log.rs
- src/node.rs
Various improvements to the message log and related code. Most notably:
- Updates the check_prepared and check_committable methods to:
* Be easier to read and understand
* Return a bool in their returned Results instead of a () to
distinguish between actual errors and the predicate simply being false
* Perform all necessary checks and verifications (i.e. did not check
if blocks matched between messages before)
- Replaces the check_msg_against_log method with a more understandable
and flexible method log_has_required_msgs
> Message log improvements

- src/handlers.rs
- src/message_log.rs
- src/node.rs
Updates `add_message` to check all messages that aren't Checkpoints or
ViewChanges to see if the view number matches the node's current view;
if it does not, do not add the message to the log. This is guarantee of
the PBFT algorithm that was not previously implemented. Also requires
passing state to `add_message`.
>  Check view number matches when adding msg to log

- Jenkinsfile
Mirrors the BuildDiscarderProperty bit from the other, older-syntax Jenkinsfiles that we have.
> Add build discarding to Jenkinsfile

- tests/test_liveness.yaml
To help diagnose the non-deterministic build failures
> More verbose liveness test logging

- src/engine.rs
- src/error.rs
- src/handlers.rs
- src/message_log.rs
- src/node.rs
- src/state.rs
Simplifies and corrects checked conditions in the PrePrepare and Commit phases; also updates the way the sequence number is tracked by basing it off of the current chain head.
> Updates to PrePrepare + Commit processes, sequence number ordering

- src/error.rs
- src/handlers.rs
- src/message_log.rs
- src/message_type.rs
- src/node.rs
- src/state.rs
Removes the hinting mechanism since it prevents the node from adding
valid messages to the log unnecessarily; as long as a message is valid
and follows the rules necessary for being added to the log, we do not
need to backlog messages until we are at the right sequence number or
phase.
Removes the water marking component of PBFT since it is not necessary.
This mechanism was designed to prevent a primary for selecting a
sequence number that was so high it exhausted the space of sequence
numbers. Because the primary does not decide the sequence number (it is
determined by the block number), it can't violate this anyway.
> Remove hinting and watermarks

- protos/pbft_message.proto
- src/config.rs
- src/error.rs
- src/handlers.rs
- src/message_extensions.rs
- src/message_log.rs
- src/message_type.rs
- src/node.rs
- src/state.rs
- tests/client.yaml
- tests/grafana.yaml
- tests/test_liveness.yaml
Removes the checkpointing procedure and all of its associated code. This
is no longer needed with the consensus seal and the guarantees that are
provided by the state management of the blockchain. Because the
blockchain stores all state history and each block is verified by a
consensus seal that consists of PBFT messages that prove the block
commit, we are never truly garbage collecting; the blockchain will
always have these messages and state changes. This makes checkpointing
unnecessary.
The following is a summary of the changes that are made by this shift:
- When a seal is verified, it's stored in the log for potential use in a
view change message
- If a view change is required, the seal for the last committed block is
included in the view change message as the equivalent to the proof …
> Remove checkpointing

- protos/pbft_message.proto
- src/config.rs
- src/engine.rs
- src/error.rs
- src/handlers.rs
- src/message_extensions.rs
- src/message_log.rs
- src/message_type.rs
- src/node.rs
- src/state.rs
- tests/client.yaml
- tests/grafana.yaml
- tests/test_liveness.yaml
Contains multiple improvements including:
- Remove WorkingBlockOption struct and replace it with a simple Option<PbftBlock>
- Get rid of unnecessary calls to service.get_chain_head when they can be replaced by using the node's state or message log
- Clean up and fix the on_block_new, on_block_commit, and catchup procedures
Based on #66
> Enhancements and fixes

- protos/pbft_message.proto
- src/config.rs
- src/engine.rs
- src/error.rs
- src/handlers.rs
- src/message_extensions.rs
- src/message_log.rs
- src/message_type.rs
- src/node.rs
- src/state.rs
- tests/client.yaml
- tests/grafana.yaml
- tests/test_liveness.yaml
Replace the `idle_timeout` and the `commit_timeout` with a single
`view_change_timeout`; this is a departure from the PBFT definition and
the view change RFC
(https://github.com/hyperledger/sawtooth-rfcs/pull/29/files).
The new timeout is roughly equivalent to the `idle_timeout`, but with
the key difference that it is stopped when a node has both a BlockNew
and a corresponding PrePrepare for the next block rather than just a
BlockNew.
This timeout will guarantee liveness in the presence of a faulty primary
by ensuring that the primary cannot indefinitely halt the network by
failing to produce a block or a PrePrepare. However, we do not need to
use a full commit timeout to ensure that a block is actually committed
on time, because whether or not a block is committed does not depend on
the …
>  Replace idle and commit timeouts with one timeout

- src/engine.rs
- src/node.rs
- src/state.rs
Remove call to the consensus service's `check_blocks` method, as well as
the `BlockValid` and `BlockInvalid` update handlers. All blocks sent
to the consensus engine by the validator have already been validated, so
there is no need to explicitly check the blocks from the consensus
engine.
Based on #70
> Remove block checking

- protos/pbft_message.proto
- src/error.rs
- src/message_extensions.rs
- src/message_log.rs
- src/message_type.rs
- src/node.rs
- src/state.rs
Improvements to PBFT's block management, including:
- Bug fixes for the catch-up procedure
- Update to make primary always initialize a new block and not try to re-use old ones
- Removal of `state.working_block`
- Updates to uphold contract with the validator that the engine will make a decision on all blocks that are sent to it
> Update block management

- docs/source/glossary.rst
Use the sphinx "glossary" directive instead of an RST table, which doesn't display properly in the HTML output.
This change allows the PBFT docs to use the "term" directive to link to a glossary term in the future.
Note: This PR simply changes the formatting. There are no changes to the terms or definitions.
> Fix PBFT glossary format

- docs/Dockerfile
- docs/source/conf.py
The PBFT docs do not need "sphinxcontrib.openapi" (it's for generating the Sawtooth REST API docs).
> Remove sphinxcontrib.openapi from doc build

- protos/pbft_message.proto
- src/message_extensions.rs
- src/message_type.rs
- src/node.rs
Implement a procedure to commit the final block in the chain when
catching up. The standard catchup procedure does not work for this,
because it requires the seal in the next block; when the node needs to
commit the last block in the chain, there is no next block yet. The
procedure works as follows:
- When a node as caught up to the 2nd-to-last block, it broadcasts a
`SealRequest` message to the network.
- When the up-to-date nodes receive the `SealRequest`, they build a
seal, package it up in a `SealResponse` message, and send the message
directly to the node that requested it.
- When the requesting node receives a `SealResponse` (it only needs one
and will ignore the others), it validates the seal and uses it to commit
the final block.
> Implement final block catchup

- src/config.rs
- src/engine.rs
- src/main.rs
- src/node.rs
- src/state.rs
- src/timing.rs
Adds the `retry_until_ok` function to the timing module, which takes a callback, a base `Duration`, and a max `Duration` as arguments; the function will repeatedly call the callback until it returns successfully (`Ok` result) using exponential backoff (the base timeout is doubled every time the callback fails, up to the maximum timeout).
The `retry_until_ok` method is used whenever `service.get_settings` is called. The base value is determined by the `exponential_retry_base` config/state field (milliseconds) and max is determined by `exponential_retry_max` (seconds); these can be configured using the `sawtooth.consensus.pbft.exponential_retry_base` and `sawtooth.consensus.pbft.exponential_retry_max` on-chain settings, respectively.
> Try again service calls

- protos/pbft_message.proto
- src/engine.rs
- src/message_log.rs
- src/node.rs
To verify the consensus seal, we need to make sure that the votes in the
seal are all from nodes that were members of the network at the time the
block was voted on. Specifically, this means that all voters should be
in the on-chain list of peers in the block prior to the one the seal
verifies.
Before this commit, the list of voters was being taken from the block
the seal verifies itself, which is incorrect. To fix this, we add the
`previous_id` field to the consensus seal when it is built, verify that
the previous ID matches the previous ID of the block when validating the
seal, and get the list of peers using the previous ID.
Also includes some other fixes that support this change.
Based on #85
> Fix seal voters list

- src/config.rs
- src/engine.rs
- src/node.rs
- src/state.rs
This commit essentially reverts some of the changes in 65466d. The
`commit_timeout`, which ensures the a block gets committed within a
specified time, allows the network to get itself "unstuck" if something
goes wrong during the commit process. This differs slightly from the
`commit_timeout` that was removed in commit 65466d; specifically, the
timer is stopped when the node decides to commit the block rather than
after the block has been committed and the engine receives the
notificaiton from the validator.
> Fix liveness bug

- docs/source/introduction-to-sawtooth-pbft.rst
- Describe PBFT at a higher level
- List the general characteristics of PBFT consensus
- Explain that PBFT networks don't allow open enrollment but admins can add nodes
- Mention some Sawtooth PBFT extensions (consensus seal and regular view changes)
- Clarify rustdoc wording
The math-heavy details will move to the Architecture section in a separate commit.
> Doc: Rewrite PBFT introduction

- src/node.rs
- src/state.rs
This fixes a bug where a node would get stuck in the `ViewChanging`
mode. The node would be able to continue to commit blocks using
catch-up, but would ignore all normal PBFT messages since it was in the
`ViewChanging` mode. This is fixed by always making sure the mode is set
to `Normal` when a block gets committed.
> Fix bug causing node to get stuck in ViewChanging

- src/node.rs
This re-implements commit 52a5f3, which was inadvertently reverted.
Before broadcasting a PrePrepare to the network when a BlockNew for the
current sequence number is received, the primary must check to make sure
that the block was the one it just created (the `signer_id` of the block
should match the node's own ID). This prevents the primary from
incorrectly broadcasting a PrePrepare if another node were to publish a
block.
> Re-implement guarded PrePrepare broadcasting

- src/message_type.rs
- src/node.rs
As part of the catch-up procedure, the node extracts all of the votes
from a valid consensus seal and adds them to its log. If the node does
this for the last block and then becomes the leader through a view
change, it will need to produce a valid consensus seal for this block.
Previously, the messages were parsed and added to the log without the
signed components, so the new seal wouldn't contain validly signed
votes. To fix this, `ParsedMessage`s can now be constructed from
`PbftSignedVote`s using the `ParsedMessage::from_signed_vote` method,
which sets the signed components of the `ParsedMessage`. The
`PbftNode::catchup` method now uses this constructor when parsing
messages from the seal.
> Add signed bytes when parsing messages from seal

- src/message_log.rs
- src/node.rs
Enforces that any block committed at sequence number n has block_num = n. This is enforced by requiring that:
1. The previous block of block n has block_num = n - 1 (this means that the block numbers of all blocks in the chain, just like sequence numbers, are strictly monotonically increasing by one)
2. The block referenced by a PrePrepare for sequence number n has block_num = n (this means that there is a strict one-to-one correlation between the sequence number and the block number)
Also updates the methods used to retrieve blocks from the log.
> Enforce block number <-> sequence number equivalence

- src/node.rs
Fixes a bug where NewView messages would be broadcasted twice; this
happened when a new primary of a 4 node network started a view change
early when it received f + 1 ViewChange messages. Because it's a 4 node
network, f=1, so f + 1 == 2f. This means that it would self-send a
ViewChange message which would trigger a NewView broadcast, then trigger
a NewView broadcast as a result of the original message that made the
count f + 1.
This is fixed by simply returning when a view change is started early;
the NewView message will still be triggered (if necessary) by the
self-sent message without sending it twice.
> Fix double-broadcasting bug for NewViews

- src/node.rs
- src/state.rs
This commit fixes a bug where a node wouldn't be able to complete the
final block catch-up procedure because it didn't update it's phase
before requesting the seal (it would still be in the Finishing phase,
but when it receives the requested seal it checks if its in the
Finishing phase to make sure it doesn't commit the block twice).
Also removes the `PbftState::reset_to_start` method since it is very
simple and only used in one place now.
> Fix state reset on commit

- protos/pbft_message.proto
- src/message_extensions.rs
- src/message_type.rs
- src/node.rs
- Add message info (message type, view, sequence number, and signer ID) to consensus seal
- Get rid of `PbftSealResponse` in favor of using the `PbftSeal` itself
- Verify implicit seal vote, view, and sequence number using the info in a seal
> Improve seal verification

- src/config.rs
- src/engine.rs
- src/node.rs
- src/state.rs
The timeout was originally called the `idle_timeout`, but was changed in
commit 65466d when the timeouts were changed; the timeouts have
essentially been reverted to their previous behavior however (with only
minor changes), so the name should be updated to more accurately reflect
its behavior again.
> Rename faulty_primary_timeout to idle_timeout

- src/node.rs
Generalizes membership updates to account for ordering of the on-chain
list (`sawtooth.consensus.pbft.peers`). Previously, if the order
changed, the local list would not be updated.
> Generalize membership changes

- src/node.rs
When a node starts up and needs to catch-up from a long way back, it may
trigger view changes such that it is on a later view than the one the
blocks it commits were committed at. In this case, the node should be
able to correct itself and adopt the views in which the blocks were
committed.
> Allow updating view backwards on catchup commit

- src/message_log.rs
- src/node.rs
- tests/test_crash_fault_tolerance.sh
Fixes the Prepare voting by not allowing the primary to broadcast a
Prepare message; the primary's PrePrepare message counts as its "vote"
for the Preparing phase. If the primary were allowed to broadcast a
Prepare, it could cause nodes to diverge on the blocks they commit for a
given sequence number when the network is a certain size.
Now, a non-faulty primary will not broadcast a Prepare message, and
non-faulty secondaries will not accept Prepare messages from the
primary. This reflects the behavior of the original PBFT definition.
> Fix primary prepare voting

- src/node.rs
This fixes a bug where while a node is waiting for a BlockCommit update
from the validator, it switches views and resets the phase to
`PrePreparing`. Even after a view change is completed, the node should
still wait for the BlockCommit notification before attempting to process
other blocks.
> Fix bug with view change while waiting for commit

- adhoc/node.yaml
- src/engine.rs
- tests/client.yaml
- tests/grafana.yaml
- tests/test_liveness.yaml
Updates the name and version that the PBFT consensus engine reports to
the validator match the conventions used in other Sawtooth projects.
> Update algorithm name and version

- src/config.rs
- src/node.rs
Replaces the existing `MockService` with a new one that, instead of just
doing nothing or returning hard-coded values, logs calls to its methods
and allows for greater flexibility of return values. Currently, it only
allows for configuration of the return values for the `get_settings` and
`summarize_block` methods, since these are the only methods where this
functionality is needed for the planned tests.
Also updates the existing node unit tests to use the `src/test_helpers.rs`.
>  Replace MockService for PbftNode unit tests

- Jenkinsfile
The devmode Jenkinsfile does this already.
Signed-off-by: Richard Berg <rberg@bitwise.io>
> Make aborted and failed builds more obvious

- src/engine.rs
- src/message_type.rs
Previously, when a PeerMessage was parsed, it was assumed that the
message came from another node. However, it is possible for a node to
send a message back to the node that created the message, in which case
the ParsedMessage.from_self field should actually be true.
This commit fixes that assumption by explicitly checking if the
message's signer ID matches the node's own ID.
> Fix from_self value of ParsedMessages from peers

- Jenkinsfile
- src/engine.rs
- src/node.rs
- src/state.rs
- tests/test_non_genesis_startup.sh
When the whole network is starting "fresh" from a non-genesis block,
none of the nodes will have the `Commit` messages necessary to build the
consensus seal for the last committed block (the chain head). To
bootstrap the network in this scenario, all nodes will send a `Commit`
message for their chain head in two cases:
1. When the node starts, if it is already connected to other peers, it
will broadcast the commits to those peers
2. Whenever one of the PBFT members connects
When > 2f + 1 nodes have connected and received these `Commit` messages,
the nodes will be able to build a seal using the messages.
This commit includes a shell script to verify the ability to restart a
network with an existing chain using the adhoc docker compose files.
Also adds this test to CI.
Signed-off-by: Logan …
> Enable restarting whole network with existing chain

- adhoc/node.yaml
- docs/source/architecture.rst
- docs/source/installing-and-running-pbft.rst
- docs/source/on-chain-settings.rst
- src/config.rs
- src/node.rs
- tests/client.yaml
- tests/grafana.yaml
- tests/test_dynamic_membership.sh
- tests/test_liveness.yaml
Rename the on-chain list of PBFT nodes from
`sawtooth.conensus.pbft.peers` to `sawtooth.consensus.pbft.members`.
This is to reduce confusion when using the term "peer" to refer to nodes
that may not be an accepted PBFT member based on the on-chain setting.
> Rename on-chain peers list

- docs/source/architecture.rst
- docs/source/glossary.rst
- docs/source/on-chain-settings.rst
Sawtooth already uses the term "peer" for static/dynamic peering, so the
PBFT doc was overloading this term. This PR changes "peer" to "(PBFT) member node"
and adds a glossary definition for "member node".
Note: The Sawtooth documentation will be fixed in a related-but-separate PR for
the hyperledger/sawtooth repo.
> Fix terminology for PBFT member nodes (was peers)

- docs/source/on-chain-settings.rst
- Add missing settings: forced_view_change_period, idle_timeout, and view_change_duration
(Note: exponential_retry_base and exponential_retry_max are no longer on-chain settings)
- Update default for commit_timeout (now 30 sec)
- Alphabetize the list
- Add tip on commands to display and change settings (with llnks to CLI doc)
- Fix format, wording, and abbreviations (sec instead of s)
- Removed unused anchor (cross-reference label)
> Update PBFT on-chain settings doc

- src/engine.rs
Errors that are the result of handling messages from other nodes
(`SigningError`s, `FaultyPrimary`s, and `InvalidMessage`s) should be
treated as warnings since they indicate a problem with other nodes, not
errors in the typical sense.
> Errors resulting from messages are warnings

- src/node.rs
- src/timing.rs
Updates the view change timeout to start only when 2f + 1 `ViewChange`
messages are received for a view. Previously, the timeout was started
when a view change was started by a node, but this is not the correct
behavior according to the PBFT paper.
> Correct view change timeout start time

- README.md
- Add link to sawtooth-core repo
- Remove status section (PBFT is no longer experimental)
- Add "Using Sawtooth PBFT Consensus" section with links to Sawtooth docs
- Condense and reorganize "About PBFT" info; add link to PBFT doc;
- Remove note on terminology diffs (will add to doc intro in a separate PR)
> Update PBFT README.md

- docs/source/introduction-to-sawtooth-pbft.rst
Removed the note saying that Sawtooth PBFT is a prototype.
Also added note on terminology differences (moved from the README).
> Doc intro: Remove prototype note; add term diffs

- docs/source/architecture.rst
The Sawtooth core docs now link directly to the PBFT architecture section.
This change provides necessary context for a user coming from the core docs.
> Add PBFT to Architecture title in doc

- docs/source/using-pbft-consensus.rst
This PR lists all names of the PBFT consensus engine: package, executable,
and service. (The existing doc shows only the package name.)
> Fix (clarify) PBFT engine name

- docs/source/using-pbft-consensus.rst
- Expand the genesis block (on-chain settings) item to say that the name is pbft and the version can be found in Cargo.toml.
- Add links to the Sawtooth core procedures in the App Dev Guide and Sys Admin Guide.
- Also clean up wording for the text that links to the full config procedures in the Sawtooth core docs.
> Add info on finding PBFT consensus name + version

- docs/source/configuring-pbft.rst
- src/main.rs
Dashes are the desired formatting for CLI options, not underscores.
> Use dashes instead of underscores in CLI option

- docs/source/configuring-pbft.rst
- docs/source/glossary.rst
- src/config.rs
- src/engine.rs
When the block_duration was renamed to block_publishing_delay, some
references to the variable in documentation and comments got missed.
This commit fixes those.
Also updates definition of commit timeout
> Fix references to block publishing delay

- docs/source/glossary.rst
This PR contains separate commits for the following changes:
- Remove math terms, because f, n, p, and v are adequately defined in the "Architecture" section.
- Remove entry for Block duration.
- Add three new terms: Consensus API, Consensus engine, Transaction family.
- Remove entries for Replica and Server; replace with a sentence under Node.
- Update View entry with info about regular view changes.
- Edit definitions to clarify and fix grammar. This commit also changes "Primary" to "Primary node" 
(ditto "Secondary node") and mentions the original PBFT paper's terms for primary and secondary.
- Alphabetize entries (in a separate commit with no technical or wording changes).
- Update Message definition (corrected and removed "block", because a message isn't a block).
- Delete Working …
> Doc: Update PBFT glossary

- CODEOWNERS
- MAINTAINERS.md
The following maintainers have asked to be retired:
Adam Ludvik, Bridger Herman, and and Kenneth Koski.
As described in the Sawtooth Governance RFC changes to maintainers must be approved unanimously by the current group of maintainers.
>  Retire Inactive Maintainers 

- Dockerfile-installed-bionic
- Dockerfile-installed-xenial
The behavior of cargo-deb was changed to generate version numbers with
tildes instead of dashes. This is causing newly built packages to sort
below older releases.
https://github.com/mmstick/cargo-deb/pull/102
> Fix versioning of pbft-engine package

- adhoc/node.yaml
- src/config.rs
- src/engine.rs
- src/message_log.rs
- src/node.rs
- src/storage/disk.rs
- src/storage/memory.rs
- src/storage/mod.rs
Updates PBFT to check blocks that it receives the validator and handle
the resulting BlockValid and BlockInvalid messages. This change is
necessary due to the Sawtooth validator being updated to validate blocks
only when specifically requested by consensus.
Overall changes made to PBFT:
- When PBFT receives a block and does its verification, it calls
`service.check_blocks` to validate the block and adds the block to the
log as an unvalidated block.
- BlockInvalid messages are handled by a new `on_block_invalid` method.
This method drops the block from the log and fails it.
- BlockValid messages are handled by a new `on_block_valid` method. This
method marks the block as valid in the log then processes the block as
usual (sends a PrePrepare, catches up, etc.).
Changes made to the log:
- …
> Check blocks and handle BlockValid/BlockInvalid

- src/message_log.rs
- src/node.rs
- src/storage/mod.rs
Fixes a bug where the requested settings for a block's grandparent block do not exist when verifying the block's consensus seal.
> Fix seal verification

- tests/test_crash_fault_tolerance.sh
- tests/test_dynamic_membership.sh
- tests/test_non_genesis_startup.sh
Updates the test scripts to trap on SIGTERM as well as EXIT to clean up
the docker containers and dump the logs. This changes ensures that the
cleanup and log dumping happens when Jenkins aborts one of the scripts,
which will aid in troubleshooting issues.
> Trap on SIGTERM in test scripts

- src/main.rs
Currently, even though the max-log-size and storage location arguments are parsed in the arguments, the values are never actually assigned to the created PbftConfig.  This resolves that so that the command works as advertised.
> Fix missing command line arg assignments

- src/node.rs
This change fixes the "bind_instead_of_map" Clippy error where an `and_then` call is used but only returns `Ok`.  This can be replaced with `map`, which doesn't require wrapping the result in a `Result`.
> Fix clippy::bind_instead_of_map

- src/timing.rs
Increases the tolerance for tests that have been causing builds to fail.
> Increase tolerance for timing tests

- src/node.rs
- tests/sawtooth-pbft-test.dockerfile
sawtooth-core is currently working toward 2.0 and may not
be compatibly with this current version of PBFT. For now
the liveness test will continue to be run against 1-3,
the "main" branch for further 1.x develpment.
Signed-off-by: Andrea Gunderson <agunde@bitwise.io>
> Pin PBFT liveness tests to 1-3 nightly validator

- src/node.rs
Fix the clippy lint "op_ref", which flags an unnecessary dereference.
> Fix op_ref clippy lint

- docs/Dockerfile
v0.17 causes builds to fail with a UnicodeDecodeError.
> Pin docutils version

- src/hash.rs
- src/message_log.rs
- src/message_type.rs
- src/node.rs
This change fixes a lint introduced with the Rust 1.54.0 release. The lint warns of borrowing an already borrowed value.
See https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow for more detail.
> Fix needless_borrow lint

- src/message_type.rs
- src/state.rs
Fixes a clippy error introduced in Rust 1.63
If a type T derives PartialEq and all of its members implement
Eq, then T can always implement Eq. Implementing Eq allows T to be
used in APIs that require Eq types. It also allows structs
containing T to derive Eq themselves.
Signed-off-by: Andrea Gunderson <agunde@bitwise.io>
> Fix derive_partial_eq_without_eq Clippy error
